version: '3'
services:

  php56: &base
    build:
      context: Dockerfiles/php56
      dockerfile: Dockerfile
    ports:
      - "8056:80"
    volumes:
      - .:/var/www/html
      - ./tmp:/tmp
    env_file:
      - .env
    networks:
      phpenv:
        ipv4_address: 10.100.110.56

  php70:
    <<: *base
    build:
      context: Dockerfiles/php70
    ports:
      - "8070:80"
    networks:
      phpenv:
        ipv4_address: 10.100.110.70

  php71:
    <<: *base
    build:
      context: Dockerfiles/php71
    ports:
      - "8071:80"
    networks:
        phpenv:
          ipv4_address: 10.100.110.71

  php72:
    <<: *base
    build:
      context: Dockerfiles/php72
    ports:
      - "8072:80"
    networks:
      phpenv:
        ipv4_address: 10.100.110.72

  mysql57:
    build:
      context: Dockerfiles/mysql57
      dockerfile: Dockerfile
    volumes:
      - ${DATABESES_BACKUP_PATH}:/opt/sql
      - .:/opt/sql_restore
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    env_file:
      - .env
    networks:
      phpenv:
        ipv4_address: 10.100.110.241

networks:
  phpenv:
    driver: bridge